spring:
  datasource:
    url: jdbc:postgresql://localhost/chestionar_auto
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  data:
    web:
      pageable:
        max-page-size: 10000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never